# Generates regions_2gis.inc: 2GIS project codes with simplified borders.
# 2GIS traffic tiles are addressed by project (city) code, the program picks it by the map center.
# Usage: python make_regions.py   (reads the 2GIS key from .env: "2gis = <key>"; the key is not stored)
import json
import urllib.request

MAX_POINTS = 40   # per ring: enough to tell neighbouring regions apart

key = [l.split("=", 1)[1].strip() for l in open(".env", encoding="utf-8") if l.strip().startswith("2gis")][0]
items, page = [], 1
while True:
    url = ("https://catalog.api.2gis.com/2.0/region/list?fields=items.bounds,items.code"
           "&page_size=50&page=%d&key=%s" % (page, key))
    res = json.load(urllib.request.urlopen(url))["result"]
    items += res["items"]
    if len(items) >= res["total"] or not res["items"]:
        break
    page += 1


def rings(wkt):
    # POLYGON((x y,...),(hole)) or MULTIPOLYGON(((...)),((...))): outer rings only
    body = wkt[wkt.index("(") :]
    out = []
    for part in body.split(")),"):
        ring = part.strip("( )").split("),(")[0]
        pts = [tuple(map(float, p.split())) for p in ring.split(",")]
        out.append(pts)
    return out


def simplify(pts):
    if len(pts) <= MAX_POINTS:
        return pts
    step = len(pts) / float(MAX_POINTS)
    return [pts[int(i * step)] for i in range(MAX_POINTS)]


def area(pts):
    return abs(sum(pts[i][0] * pts[i - 1][1] - pts[i - 1][0] * pts[i][1] for i in range(len(pts)))) / 2


regs = []
for it in items:
    for r in rings(it["bounds"]):
        s = simplify(r)
        regs.append((area(s), it["code"], s))
regs.sort()   # smaller first: a city wins over the region around it

points, table = [], []
for a, code, s in regs:
    xs, ys = [p[0] for p in s], [p[1] for p in s]
    table.append('    { "%s", %.4ff, %.4ff, %.4ff, %.4ff, %d, %d },' % (code, min(xs), min(ys), max(xs), max(ys), len(points), len(s)))
    points += s

out = ["/* Generated by make_regions.py from the 2GIS Catalog API region list. Do not edit. */\n",
       "struct Region2Gis { const char* code; float lon0, lat0, lon1, lat1; int first, count; };\n\n",
       "static const float kRegionPoints[][2] = {\n"]
out += ["    { %.4ff, %.4ff },\n" % p for p in points]
out.append("};\n\nstatic const Region2Gis kRegions[] = {\n")
out.append("\n".join(table))
out.append("\n};\n\n#define REGION_COUNT (sizeof(kRegions) / sizeof(kRegions[0]))\n")
open("regions_2gis.inc", "w", newline="\n").write("".join(out))
print("regions:", len(regs), "points:", len(points))
