# Generates trust_anchors.inc: root certificates for BearSSL, taken from a PEM bundle.
# Usage: python make_ta.py [ca-bundle.crt]
# VS2005 has no designated initializers, so the anchors are filled in by a function.
import sys
from cryptography import x509
from cryptography.hazmat.primitives.asymmetric import rsa, ec
from cryptography.hazmat.primitives import serialization

BUNDLE = sys.argv[1] if len(sys.argv) > 1 else r"C:\Program Files\Git\mingw64\etc\ssl\certs\ca-bundle.crt"

# Roots of the servers we use (OSM: GlobalSign R3, Yandex: GlobalSign R46/R3)
# plus the most common CAs, so a certificate change on a server
# does not break the program.
WANTED = [
    "GlobalSign Root CA - R3", "GlobalSign Root R46", "GlobalSign Root E46", "GlobalSign Root CA",
    "ISRG Root X1", "ISRG Root X2",
    "DigiCert Global Root CA", "DigiCert Global Root G2", "DigiCert Global Root G3",
    "IdenTrust Commercial Root CA 1",
    "USERTrust RSA Certification Authority", "USERTrust ECC Certification Authority",
    "GTS Root R1", "GTS Root R2", "GTS Root R3", "GTS Root R4",
    "Amazon Root CA 1", "Amazon Root CA 2", "Amazon Root CA 3", "Amazon Root CA 4",
]

CURVES = {"secp256r1": 23, "secp384r1": 24, "secp521r1": 25}


def name_of(cert):
    # GlobalSign R3 has CN "GlobalSign" and OU "GlobalSign Root CA - R3"
    for oid in (x509.NameOID.ORGANIZATIONAL_UNIT_NAME, x509.NameOID.COMMON_NAME):
        attrs = cert.subject.get_attributes_for_oid(oid)
        if attrs and attrs[0].value in WANTED:
            return attrs[0].value
    return None


def carray(name, data):
    items = ["0x%02X" % b for b in data]
    lines = [",".join(items[i:i + 16]) for i in range(0, len(items), 16)]
    return "static const unsigned char %s[] = {\n    %s\n};\n" % (name, ",\n    ".join(lines))


pem = open(BUNDLE, "rb").read()
certs = x509.load_pem_x509_certificates(pem)
found = {}
for c in certs:
    n = name_of(c)
    if n and n not in found:
        found[n] = c

missing = [w for w in WANTED if w not in found]
out = ["/* Generated by make_ta.py from %s. Do not edit. */\n" % BUNDLE.replace("\\", "/")]
init = []
for i, n in enumerate(w for w in WANTED if w in found):
    c = found[n]
    out.append("/* %s, valid until %s */\n" % (n, c.not_valid_after_utc.date()))
    out.append(carray("TA%d_DN" % i, c.subject.public_bytes(serialization.Encoding.DER)))
    k = c.public_key()
    init.append("    ta[%d].dn.data = (unsigned char*)TA%d_DN; ta[%d].dn.len = sizeof(TA%d_DN);" % (i, i, i, i))
    init.append("    ta[%d].flags = BR_X509_TA_CA;" % i)
    if isinstance(k, rsa.RSAPublicKey):
        nums = k.public_numbers()
        nb = nums.n.to_bytes((nums.n.bit_length() + 7) // 8, "big")
        eb = nums.e.to_bytes((nums.e.bit_length() + 7) // 8, "big")
        out.append(carray("TA%d_N" % i, nb))
        out.append(carray("TA%d_E" % i, eb))
        init.append("    ta[%d].pkey.key_type = BR_KEYTYPE_RSA;" % i)
        init.append("    ta[%d].pkey.key.rsa.n = (unsigned char*)TA%d_N; ta[%d].pkey.key.rsa.nlen = sizeof(TA%d_N);" % (i, i, i, i))
        init.append("    ta[%d].pkey.key.rsa.e = (unsigned char*)TA%d_E; ta[%d].pkey.key.rsa.elen = sizeof(TA%d_E);" % (i, i, i, i))
    else:
        q = k.public_bytes(serialization.Encoding.X962, serialization.PublicFormat.UncompressedPoint)
        out.append(carray("TA%d_Q" % i, q))
        init.append("    ta[%d].pkey.key_type = BR_KEYTYPE_EC;" % i)
        init.append("    ta[%d].pkey.key.ec.curve = %d;" % (i, CURVES[k.curve.name]))
        init.append("    ta[%d].pkey.key.ec.q = (unsigned char*)TA%d_Q; ta[%d].pkey.key.ec.qlen = sizeof(TA%d_Q);" % (i, i, i, i))
count = len(found)
out.append("\n#define TA_COUNT %d\n\n" % count)
out.append("static void InitTrustAnchors(br_x509_trust_anchor* ta)\n{\n    memset(ta, 0, TA_COUNT * sizeof(*ta));\n")
out.append("\n".join(init))
out.append("\n}\n")
open("trust_anchors.inc", "w", newline="\n").write("".join(out))
print("anchors:", count, "missing:", missing)
